spring:
  data:
    mongo:
      uri: ${MONGO_URI:mongodb://localhost:27017/cadastro_generico}


app:
  clients:
    viacep:
      base-url: https://viacep.com.br/ws


  messages:
    basename: messages
    encoding: UTF-8