spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/cadastrodb?authSource=admin
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100

app:
  clients:
    viacep:
      base-url: https://viacep.com.br/ws
  messages:
    basename: messages
    encoding: UTF-8


api:
  security:
    token:
      secret: "security-aip-token-secret-name-generic-registration"