services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" # <-- ESTA Ã‰ A PONTE



app:
  clients:
    viacep:
      base-url: https://viacep.com.br/ws


  messages:
    basename: messages
    encoding: UTF-8